### ISSUE TITLE
Unable to use deleteOne with _id

### ISSUE THREAD

**Issue by chris-mclennan** [Zaista/cypress-mongodb#20]
When attempting to use deleteOne with _id it does not work for me but when I use other key/values I can get it to delete.  I dont know what I am doing wrong.  I can use another mongo package and delete by _id and new ObjectId('634d732c5bcba068900dfc94').  I am using import { ObjectId } from 'mongodb';

This code works:
`             const filter = { 'merchant': 1234, 'isActive': true }
              const options = { collection: 'Locations' }
              cy.deleteOne(filter, options).then((results: any) => {
                cy.log('results', results) // Yielded:  1 document deleted
              })`

This code fails:
`             const filter = { _id: new ObjectId('634d732c5bcba068900dfc94') }
              const options = { collection: 'Locations' }
              cy.deleteOne(filter, options).then((results: any) => {
                cy.log('results', results) // Yielded:  0 document deleted
              })`

**Comment by Zaista** [comment]
Thank you for raising this issues. Indeed, the handling of complex object types were missing. It is fixed in version 5.1.2 which is already published on npm. Happy testing!
