### ISSUE TITLE
Error: Webpack Compilation Error when we set const mongo = require('cypress-mongodb'); mongo.addCommands();

### ISSUE THREAD

**Issue by matifniaz** [Zaista/cypress-mongodb#22]
**As per your provided configuration, When we added the below lines and run our spec file we got this error.**

In your cypress/support/e2e.js add the following:
**const mongo = require('cypress-mongodb');
mongo.addCommands();**

Spec file snapshot attahced for refernece.

![image](https://user-images.githubusercontent.com/40147842/197127656-196417c3-11b1-49b7-8945-cb6a143cd7e5.png)

Error snapshot is attached for reference.
![image](https://user-images.githubusercontent.com/40147842/197127599-45e81336-944d-458f-8b9c-039a68de5e7e.png)
Pakage,json 
`{
  "name": "cypress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cypress": "^10.9.0",
    "cypress-downloadfile": "^1.2.3",
    "npm-check-updates": "^16.3.11"
  },
  "devDependencies": {
    "cypress-file-upload": "^5.0.8",
    "cypress-mochawesome-reporter": "^3.2.3",
    "cypress-xpath": "^2.0.1",
    "multiple-cucumber-html-reporter": "^3.0.1"
  }
}
`

**Comment by chris-mclennan** [comment]
I too have this same problem.  When I comment out the two commands matifniaz mentions, the error goes away and cypress will run tests as long as they do not reference one of the cypress-mongodb commands.  
![image](https://user-images.githubusercontent.com/88120746/197934957-f2a29357-6b35-442b-ba19-0d20113c4134.png)

**Comment by Zaista** [comment]
Thanks for raising the issue, will take a look over the weekend.

**Comment by chris-mclennan** [comment]
If you come across any way to get around it please share.  I cant use Cypress without turning off a lot of tests and cypress-mongodb

**Comment by chris-mclennan** [comment]
I found a workaround by renaming the node_modules/@aws-sdk folder.  After that I could run tests

**Comment by chris-mclennan** [comment]
I found another temporary workaround by removing all references to @aws-sdk from package-lock.json and running npm install again.

**Comment by wilson208** [comment]
For anyone else running into this, in latest mongodb release [4.11.0](https://github.com/mongodb/node-mongodb-native/blob/HEAD/HISTORY.md#4110-2022-10-19) they made aws-sdk dependencies optional.

To fix this error you can update to latest mongodb version and re-install dependencies with `yarn install --ignore-optional`. You may need to delete `node_modules` and `yarn.lock` for this to work.

**Comment by raialmeida** [comment]
Hi, I'm having the same problem.

**Comment by dgoerdes** [comment]
As @wilson208 wrote, it is the mongodb dependency which causes the issue.
I downgraded to version 4.10.0, and it works.

**Comment by Zaista** [comment]
Should be fixed with the latest version I just publish, but I'm not quite sure tbh, this was a tricky one. Please let me know if you encounter more issues
