### ISSUE TITLE
insertOne command returns wrong error

### ISSUE THREAD

**Issue by PabloRamirezDev** [Zaista/cypress-mongodb#3]
The insertOne command throws the error `Pipeline must be an object`, although it doesn't receive any `pipeline` parameter. 

Checked the source code and could solve it changing `args.pipeline` by `args.document` in the `insertOne` util.

**Comment by Zaista** [comment]
Feel free to fork, fix & open PR, otherwise I'll try and do it over the weekend. Thanks for raising the issue.

**Comment by Zaista** [comment]
Merged, and v2.1.2 published to npm.
