### ISSUE TITLE
Please write a clear documentation on how to use ObjectId with Cypress-mongodb

### ISSUE THREAD

**Issue by nivedhamanoharan** [Zaista/cypress-mongodb#33]
I am getting the below error if I try to use mongo or bson plugins
![image](https://user-images.githubusercontent.com/14906112/230747585-f7961b25-1f94-42a4-bd61-90b7682b1f40.png)

**Comment by Zaista** [comment]
Could you please share some code examples which cause the error?
Right now, all I can see is that error comes because of the Nullish coalescing operator, which has nothing to do with cypress-mongodb plugin. It could mean you just have the older version of node installed that doesn't support it. Could you upgrade to the latest one and recheck?

**Comment by nivedhamanoharan** [comment]
Hi @Zaista ,

Thank you for the reply. I am using the latest node version Node.js v18.14.2.

When I try to import { ObjectId } from 'mongodb', I am getting the above error.
So I tried to use bson-objectid plugin to use ObjectId.

`import ObjectID from "bson-objectid";

Cypress.Commands.add('getKeyValueFromArray', (key: any, array: any) => {
  let result: any;
  array.forEach((element: any) => {
    result = element.hasOwnProperty(key) ? element[key] : result;
  });
  return cy.wrap(result);
});

Cypress.Commands.add('getArrayElement', (key: any, value: any, array: any) => {
  let result: any;
  array.forEach((element: any) => {
    result = element[key] === value ? element : result;
  });
  return cy.wrap(result);
});

Cypress.Commands.add('getObjectId', (value: string) => {
  return cy.wrap(new ObjectID(value));
});
`

Usage here:
`cy.getObjectId(testData).then((result: any) => {
          filter = { _id: result };
          console.log(filter);
        }).then(() => {
          dbBuilder(databases.main, <Collection_name>)
            .connect()
            .findDocument(filter)`

But Still, It does not filter the documents.

**Comment by Zaista** [comment]
I think I know what's causing it, but sadly don't know how to solve it properly except downgrading to mongodb version 4.10.0 in your node project.
Could you give that a go and let me know if at least that works?

**Comment by nivedhamanoharan** [comment]
Hi @Zaista , thank you so much. I found a plugin '@tybys/oid' which does the trick.

Can you please let me know if I can switch databases dynamically when the tests are running? If not, I think it would be a good feature to expose for this plugin.
