### ISSUE TITLE
Insert One Document always returns a duplicated default set of data

### ISSUE THREAD

**Issue by Lisa-V-Sau** [Zaista/cypress-mongodb#40]
Hi, 

I'm using the Insert One method to insert data into my db, however it always returns my data as an object plus with an default set like the following:

-object()
--data
-default
---object
----data

I am unclear as to why its seeding my data in this form but is there anyway to just store it without either objects or defaults and just the data itself??

Appreciate the help, thanks!

Lisa

**Comment by Zaista** [comment]
Hi, thanks for raising the issue. I'm on vacation now, but will take a look as soon as I'm back.

**Comment by Zaista** [comment]
Do you mind sharing an example how to reproduce it? In the examples I use, insertOne works as expected...
