### ISSUE TITLE
Add function to list collections in the database

### ISSUE THREAD

**Issue by akshatdalton** [Zaista/cypress-mongodb#41]
Can we please add the function to list collections in the database?

**Comment by akshatdalton** [comment]
If you would give me a green flag, then I can raise the PR for the same.

In fact, I believe there should be a separate command that this package should support to execute custom commands (like `ping`).

**Comment by Zaista** [comment]
Hi, please feel free to raise a PR, just bear in mind I won't be able to review it in the next two weeks. Thanks

**Comment by Zaista** [comment]
Released v6.1.0 that adds `runCommand` in which you can send `listCollections`, `ping`, and other commands to mongodb
