### ISSUE TITLE
ObjectId type is not working

### ISSUE THREAD

**Issue by joshmedeski** [Zaista/cypress-mongodb#5]
Great library, the API is simple and I'm thankful for TypeScript support.

# The Problem

I want to hard code the `_id` on an inserted user. When I pass the 

```ts
import { ObjectId } from "MongoDB";

describe("login", () => {
  beforeEach(() => {
    cy.deleteMany({}, "users");
    const objectId = new ObjectId();

    const user = {
      _id: objectId,
      ...otherFields
    };

    cy.insertOne(user, "users").then((res) => {
      cy.log(JSON.stringify(res));
    });
```

When I run this, the objectId is inserted as a string on the mongoDb model (see Compass screenshot below).

<img width="239" alt="Screen Shot 2022-03-10 at 1 07 23 PM" src="https://user-images.githubusercontent.com/2036594/157737055-74e0e7c3-69a6-4e06-bb63-b95ae2697157.png">

If I remove the `_id` field in the payload, the system is able to autogenerate a valid `ObjectId` on the mongo entry.

<img width="341" alt="Screen Shot 2022-03-10 at 1 06 36 PM" src="https://user-images.githubusercontent.com/2036594/157737220-6a0c8a09-c1a3-4a25-b52c-2da34b16459f.png">

What's going on? Why is the `ObjectId` object being converted to a string on the insert?

I looked into the `forceServerObjectId` on the insert options but haven't had any success figuring it out.

**Comment by Zaista** [comment]
Hey, thanks for posting the issue. I haven't had the time to fix it during the weekend, but I will as soon as I get a chance for it
