### ISSUE TITLE
The new objectId change is causing me problems.

### ISSUE THREAD

**Issue by teebu** [Zaista/cypress-mongodb#8]
`args.pipeline._id = new ObjectId(args.pipeline._id);`

This is causing me problems. Please add this as an option not force all strings to be automatically ObjectId. 
I rely on it to stay a string.

https://www.mongodb.com/docs/manual/reference/method/ObjectId/
![image](https://user-images.githubusercontent.com/5531844/167173610-277e2121-7bde-4896-b7e5-6d1a2d7dcb96.png)

**Comment by Zaista** [comment]
Hey, thanks for raising the issue. I'm fixing it atm, though it will require some overhaul to the plugin, and a major release. So it will take me a few more days. For now, please just use the older version of the plugin and I'll close this issue when the new version is released.
